/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: "#0d1320",
        "surface-dim": "#0d1320",
        "surface-bright": "#333948",
        "surface-container-lowest": "#080e1b",
        "surface-container-low": "#161b29",
        "surface-container": "#1a1f2d",
        "surface-container-high": "#242a38",
        "surface-container-highest": "#2f3543",
        "on-surface": "#dde2f5",
        "on-surface-variant": "#d8c3ad",
        outline: "#a08e7a",
        "outline-variant": "#534434",
        primary: "#ffc174",
        "on-primary": "#472a00",
        "primary-container": "#f59e0b",
        "on-primary-container": "#613b00",
        secondary: "#adc6ff",
        "on-secondary": "#002e6a",
        tertiary: "#56e5a9",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        background: "#0d1320",
        "on-background": "#dde2f5",

        // Colores semánticos tácticos (del apartado "Components")
        critical: "#EF4444",
        warning: "#F97316",
        caution: "#FBBF24",
        operational: "#10B981",
        telemetry: "#3B82F6",
      },
      fontFamily: {
        heading: ["PlusJakartaSans"],
        body: ["Inter"],
      },
      fontSize: {
        "headline-xl": "32px",
        "headline-lg": "24px",
        "headline-md": "20px",
        "headline-sm": "18px",
        "body-lg": "16px",
        "body-md": "14px",
        "body-sm": "12px",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
      },
      spacing: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
      },
    },
  },
  plugins: [],
};
